variables:
  GIT_CLEAN_FLAGS: none # disable git clean on every stage
  CODECOV_TOKEN: "064fad14-0241-4b7a-9c86-ab7b5ed067a3"
  MIRROR_DIR:  .mirror
  GITHUB_REPO: https://github.com/yallie/MdlpClient.git
  GITHUB_USER: yallie

stages:
  - build
  - unit tests
  - mirror

build:
  stage: build
  before_script:
    - git clean -ffdx -e $MIRROR_DIR/
  script:
    - dotnet build

unit_tests:
  stage: unit tests
  before_script:
    - echo "Normal build -- running unit tests with coverage..."
    # uncomment to install the required tools --
    # dotnet tool install -g trx2junit
    # choco install opencover.portable
    # choco install codecov
  script:
    # original test command line --
    # dotnet test --logger "trx;LogFileName=TestResults.trx"
    # don't use -returntargetcode for now
    # 'OpenCover.Console.exe -register:administrator -target:dotnet.exe -targetargs:"test --logger=trx;LogFileName=TestResults.trx" -filter:"+[*]* -[*Test*]*" -output:MdlpCoverage.xml'
    # codecov -f "MdlpCoverage.xml"
    - Scripts\Coverage.ps1
  artifacts:
    paths:
      - MdlpApiClient.Tests\TestResults\TestResults.trx 
      - MdlpApiClient.Tests\TestResults\TestResults.xml
    reports:
      junit: MdlpApiClient.Tests\TestResults\TestResults.xml
    expire_in: 1 day

mirror:
  stage: mirror
  before_script:
    - echo "Push changes to github mirror..."
  script:
    - Scripts\Mirror.ps1 
      -remote github
      -repo   $CI_REPOSITORY_URL 
      -dir    $MIRROR_DIR
      -url    $GITHUB_REPO
      -user   $GITHUB_USER
      -token  $GITHUB_TOKEN
